version: '3'
services:
  web:
    image: react-test-course
    build:
      context: ./
      dockerfile: Dockerfile.dev
    container_name: web
    ports:
      - 3000:3000
    volumes:
      - ./src:/app/src
      - ./public:/app/public
  prod:
    image: react-prod
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: web_prod
    ports:
      - 8080:80
